=== giovanni-venturelli/arsr/data/xsd/login.xsd
<?xml version="1.0"?>
	<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

			<xs:element name="login">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Utente" type="utn" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
				<xs:complexType name="utn">
					<xs:sequence>
						<xs:element name="username" type="xs:string" />
						<xs:element name="mail">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="([a-zA-Z0-9]+)(@[a-z]+).(it|com)"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="password">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="4"/>
									<xs:maxLength value="8"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="nome" type="xs:string" />
						<xs:element name="cognome" type="xs:string" minOccurs="0" />
						<xs:element name="indirizzo" type="ind" />
						<xs:choice>
								<xs:element name="CF">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:pattern value="[A-Z0-9]*"/>
											<xs:length value="16"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="PI">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:pattern value="[0-9]*" />
											<xs:length value="11"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
						</xs:choice>
					</xs:sequence>
				</xs:complexType>
				<xs:complexType name="ind">
					<xs:sequence>
						<xs:element name="via" type="xs:string" />
						<xs:element name="numero">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="([0-9])+[a|b]*" />
									<xs:maxLength value="3" />
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="paese" type="xs:string" />
						<xs:element name="provincia" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:schema>

=== giovanni-venturelli/arsr/data/login.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xmlns = "http://www.ASRS.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="login.xsd"?>
<login>
	<Utente>
		<username>user1</username>
		<mail>user1@gmail.com</mail>
		<password>user</password>
		<nome>nome</nome>
		<cognome>cognome</cognome>
		<indirizzo>
			<via>via</via>
			<numero>1</numero>
			<paese>paese</paese>
			<provincia>provincia</provincia>
		</indirizzo>
		<CF>GMTLKS45862DF89S</CF>
	</Utente>
	<Utente>
		<username>user2</username>
		<mail>user2@gmail.com</mail>
		<password>user</password>
		<nome>nome</nome>
		<indirizzo>
			<via>via</via>
			<numero>1</numero>
			<paese>paese</paese>
			<provincia>provincia</provincia>
		</indirizzo>
		<PI>12345678901</PI>
	</Utente>
</login>
