=== giovanni-venturelli/arsr/data/xsd/staff.xsd
<?xml version="1.0"?>
	<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

		<xs:element name="Database">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="persona" type="pers" maxOccurs="unbounded" minOccurs="0"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		
		<xs:complexType name="pers">
				<xs:sequence>
					<xs:element name="id" type="xs:string"/>
				
					<xs:element name="nome" type="xs:string"/>
					
					<xs:element name="cognome" type="xs:string"/>
					
					<xs:element name="ruolo" type="xs:string"/>
				
					<xs:element name="img" type="imm"/>

				</xs:sequence>
				
			</xs:complexType>
					<xs:complexType name="imm">
						<xs:sequence>
							<xs:element name="source" type="xs:string" />
							<xs:element name="alt" type="xs:string" />
						</xs:sequence>
			</xs:complexType>
			
	</xs:schema>

=== giovanni-venturelli/arsr/data/staff.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="staff.xsl"  xmlns="http://www.ASRS.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="xsd/staff.xsd"?>
<Database>
	

<persona>
	<id>5</id>
	<nome>Paolo</nome>
	<cognome>Tizianel</cognome>
	<ruolo>fonico</ruolo>
	<img>
		<source>arsr.jpg</source>
		<alt>Foto di Paolo Tizianel</alt>
	</img>
</persona>

<persona>
	<id>6</id>
	<nome>Leonardo</nome>
	<cognome>Benetollo</cognome>
	<ruolo>capo</ruolo>
	<img>
		<source>arsr.jpg</source>
		<alt>Foto di Leonardo Benetollo</alt>
	</img>
</persona>

<persona>
	<id>1</id>
	<nome>Francesco</nome>
	<cognome> Agostini</cognome>
	<ruolo>Presidente</ruolo>
	<img>
		<source>cesco.jpg</source>
		<alt>Foto di Francesco  Agostini</alt>
	</img>
</persona>
<persona>
	<id>4</id>
	<nome>stolfo</nome>
	<cognome>fent</cognome>
	<ruolo>fonico</ruolo>
	<img>
		<source>impossible-triangle-md.png</source>
		<alt>Foto di stolfo fent</alt>
	</img>
</persona></Database>
