=== giovanni-venturelli/arsr/daUppare/data/xsd/attrezzature.xsd
<?xml version="1.0"?>
	<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
		<xs:element name="database">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="attrezzatura" type="attr" maxOccurs="unbounded" minOccurs="0"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>

			<xs:complexType name="attr">
				<xs:sequence>
					<xs:element name="nome" type="xs:string"/>
					<xs:element name="codice_prodotto">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:pattern value="[0-9]*" />
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="descrizione">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="0"/>
								<xs:maxLength value="50"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="prezzo">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:pattern value="[0-9]*â‚¬"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="img" type="imm"/>
					<xs:element name="disponibile">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:pattern value="si|no|disponibile tra [1-9] giorni"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
					<xs:complexType name="imm">
						<xs:sequence>
							<xs:element name="source" type="xs:string" />
							<xs:element name="alt" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
	</xs:schema>

=== giovanni-venturelli/arsr/data/attrezzature.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="attrezzature.xsl"  xmlns="http://www.ASRS.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="attrezzature.xsd"?>
<database>	
	<attrezzatura>
				<nome>Microfono Shure sm57</nome>
				<codice_prodotto>1</codice_prodotto>
				<descrizione>Microfono dinamico per strumenti</descrizione>
				<prezzo>5 </prezzo>
				<img>
					<source>sm57.jpg</source>
					<alt>Microfono Shure sm57 </alt>
				</img>
				<disponibile>disponibile</disponibile>
	</attrezzatura>
	<attrezzatura>
				<nome>Microfono Shure sm58</nome>
				<codice_prodotto>2</codice_prodotto>
				<descrizione>Microfono dinamico per voce/strumenti </descrizione>
				<prezzo>5 euro</prezzo>
				<img>
					<source>sm58.jpg</source>
					<alt>Microfono Shure sm57 </alt>
				</img>
				<disponibile>disponibile</disponibile>
	</attrezzatura>
	
	<attrezzatura>
				<nome>Shure beta 58A</nome>
				<codice_prodotto>3</codice_prodotto>
				<descrizione>Microfono specifico per il canto</descrizione>
				<prezzo>6 €</prezzo>
				<img>
					<source></source>
					<alt>Shure beta 58A</alt>
				</img>
				<disponibile>disponibile</disponibile>
	</attrezzatura>
	
	<attrezzatura>
				<nome>AKG c1000</nome>
				<codice_prodotto>4</codice_prodotto>
				<descrizione>Microfono dinamico da voce</descrizione>
				<prezzo>7 €</prezzo>
				<img>
					<source>AKG-c1000.jpg</source>
					<alt>AKG c1000</alt>
				</img>
				<disponibile>disponibile</disponibile>
	</attrezzatura>
	<attrezzatura>
				<nome>DrumSet T.Bone 4xCD55 1xBD200</nome>
				<codice_prodotto>5</codice_prodotto>
				<descrizione>kit microfono da batteria</descrizione>
				<prezzo>10 €</prezzo>
				<img>
					<source>/kitbatteria.jpg</source>
					<alt>DrumSet T.Bone 4xCD55 1xBD200</alt>
				</img>
				<disponibile>disponibile</disponibile>
	</attrezzatura>
	
<attrezzatura>
			<nome>Monitor The Box M1520 (300W)</nome>
			<codice_prodotto>6</codice_prodotto>
			<descrizione>monitor passivo 300 watt</descrizione>
			<prezzo>15 €</prezzo>
			<img>
				<source>monitortbox.jpg</source>
				<alt>Monitor The Box M1520 (300W)</alt>
			</img>
			<disponibile>disponibile</disponibile>
		</attrezzatura>
<attrezzatura>
			<nome>SoundCraft 38Ch</nome>
			<codice_prodotto>7</codice_prodotto>
			<descrizione>mixer analogico 38 canali</descrizione>
			<prezzo>25 €</prezzo>
			<img>
				<source>soundcragt32.jpg</source>
				<alt>SoundCraft 38Ch</alt>
			</img>
			<disponibile>disponibile</disponibile>
		</attrezzatura>

<attrezzatura>
			<nome>Mixer Allen and Heath 16Ch</nome>
			<codice_prodotto>8</codice_prodotto>
			<descrizione>mixer analogico 16 canali</descrizione>
			<prezzo>15 €</prezzo>
			<img>
				<source>makie16.jpg</source>
				<alt>Allen and Heath 16Ch</alt>
			</img>
			<disponibile>disponibile</disponibile>
		</attrezzatura>

<attrezzatura>
			<nome>Behringer 8ch</nome>
			<codice_prodotto>9</codice_prodotto>
			<descrizione>mixer eurorack 16</descrizione>
			<prezzo>10 €</prezzo>
			<img>
				<source>behringer.jpg</source>
				<alt>Behringer 8ch</alt>
			</img>
			<disponibile>disponibile</disponibile>
		</attrezzatura>

</database>
