=== giovanni-venturelli/arsr/daUppare/data/xsd/feedback.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="commenti">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="feedback" type="commento" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="commento">
		<xs:sequence>
			<xs:element name="id" type="xs:integer"/>
			<xs:element name="autore" type="xs:string"/>
			<xs:element name="immagine">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="((.){0,2}\/)?([a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*(\/)?)*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="data" type="xs:date"/>
			<xs:element name="corpo"/>
			</xs:sequence>
		</xs:complexType>
	</xs:schema>

=== giovanni-venturelli/arsr/daUppare/data/feedback.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xmlns = "http://www.ASRS.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="feedback.xsd"?>
<commenti>
	<feedback>
		<id>1</id>
		<autore>frossi</autore>
		<immagine>avatar.jpg</immagine>
		<data>2015-05-07</data>
		<corpo>Un servizio eccellente! professionalita' e cortesia a un prezzo vantaggioso</corpo>
	</feedback>
	<feedback>
		<id>2</id>
		<autore>francesco10</autore>
		<immagine>avatar.jpg</immagine>
		<data>2015-05-03</data>
		<corpo>La mia festa di compleanno non poteva risultare piu' spettacolare! grazie!</corpo>
	</feedback>
	<feedback>
		<id>3</id>
		<autore>alessiaT</autore>
		<immagine>avatar.jpg</immagine>
		<data>2015-01-22</data>
		<corpo>Servizio ottimo! anche se con poco preavviso, hanno saputo accontentarmi in tutto! </corpo>
	</feedback>

</commenti>

=== giovanni-venturelli/arsr/data/feedback.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xmlns = "http://www.ASRS.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="feedback.xsd"?>
<commenti>
	<feedback>
		<id>1</id>
		<autore>AstroSamantha</autore>
		<immagine>avatar.jpg</immagine>
		<data>2015-05-07</data>
		<corpo>Un servizio stellare!</corpo>
	</feedback>
	<feedback>
		<id>2</id>
		<autore>SilvioBerlusconi</autore>
		<immagine>avatar.jpg</immagine>
		<data>2015-05-03</data>
		<corpo>Cribio!</corpo>
	</feedback>
	<feedback>
		<id>3</id>
		<autore>DanteAlighieri</autore>
		<immagine>avatar.jpg</immagine>
		<data>2015-01-22</data>
		<corpo>Tanto gentile e tanto onesta pare la donna mia quando altrui saluta ch'ogne lingua deven tremando muta e li occhi no l'ardiscon di guardare. Ella si va sentendosi laudare benignamente d'umiltà vestuta e par che sia cosa venuta di cielo in terra a miracol mostrare. Mostrasi sì piacente a chi la mira che dà per li occhi una dolcezza al core che intender no la può chi no la prova.</corpo>
	</feedback>


<feedback>
				<id>6</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>3</corpo>
				</feedback>
<feedback>
				<id>7</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>4</corpo>
				</feedback>
<feedback>
				<id>8</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>5</corpo>
				</feedback>
<feedback>
				<id>9</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>6</corpo>
				</feedback>
<feedback>
				<id>10</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>7</corpo>
				</feedback>
<feedback>
				<id>11</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>8</corpo>
				</feedback>
<feedback>
				<id>12</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>9</corpo>
				</feedback>
<feedback>
				<id>13</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>11</corpo>
				</feedback>
<feedback>
				<id>14</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>12</corpo>
				</feedback>
<feedback>
				<id>15</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>13</corpo>
				</feedback>
<feedback>
				<id>16</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>15</corpo>
				</feedback>
<feedback>
				<id>17</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>16</corpo>
				</feedback>
<feedback>
				<id>18</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>17</corpo>
				</feedback>
<feedback>
				<id>19</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>18</corpo>
				</feedback>

<feedback>
				<id>21</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>20</corpo>
				</feedback>
<feedback>
				<id>22</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-13</data>
				<corpo>21</corpo>
				</feedback>
<feedback>
				<id>23</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-14</data>
				<corpo>22</corpo>
				</feedback>
<feedback>
				<id>24</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-14</data>
				<corpo>%\div% %\div% che palle</corpo>
				</feedback>
<feedback>
				<id>25</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-14</data>
				<corpo>]/div[]/div[</corpo>
				</feedback>

<feedback>
				<id>26</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-14</data>
				<corpo>prova</corpo>
				</feedback>


<feedback>
				<id>27</id>
				<autore>giovanni</autore>
				<immagine>avatar.jpg</immagine>
				<data>2015-05-27</data>
				<corpo>ddd</corpo>
				</feedback>
</commenti>
