=== giovanni-venturelli/arsr/daUppare/data/xsd/index.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="main">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="frame" minOccurs="3" maxOccurs="3">
					<xs:complexType>
							<xs:sequence>
								<xs:element name="titolo">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="1"/>
											<xs:maxLength value="200"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="corpo">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="1"/>
											<xs:maxLength value="20000"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
							</xs:sequence>
						<xs:attribute name="id" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== giovanni-venturelli/arsr/daUppare/data/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xmlns = "http://www.ASRS.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="index.xsd"?>
<main>
	
	
	
	
	
	
	
			
			
	
			
			
	
			
			
	
			
			
	
			
			
	
			
			
	<frame>
			<id>uno</id>
			<titolo>Musica Dal Vivo</titolo>
			<corpo>Per eventi musicali, dal piccolo locale alla piazza del paese, abbiamo a disposizione attrezzature audio per ogni tipo di esigenza.</corpo>
			</frame>
			<frame>
			<id>due</id>
			<titolo>DJ set live</titolo>
			<corpo>Festa di compleanno? Voglia di ballare? Vuoi rendere indimenticabile il tuo 18° compleanno? Perché spendere milioni per far la festa in discoteca quando la discoteca puoi farla a casa tua? Abbiamo impianti su misura per feste domestiche fino alle sale più grandi.</corpo>
			</frame>
			<frame>
			<id>tre</id>
			<titolo>Studio Recording</titolo>
			<corpo>Hai una band e vorresti registrare una demo? Hai il pezzo del secolo in mente e vorresti registrarlo? Spesso e volentieri gli studi per registrare una semplice demo, offrendo servizi di altissimo livello e strutture hanno prezzi inaccessibili ai privati e alle band emergenti.</corpo>
			</frame>
</main>
