=== giovanni-venturelli/arsr/daUppare/data/xsd/login.xsd
<?xml version="1.0"?>
	<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

			<xs:element name="login">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="utente" type="utn" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
				<xs:complexType name="utn">
					<xs:sequence>
						<xs:element name="username" type="xs:string" />
						<xs:element name="email">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="([a-zA-Z0-9]+)(@[a-z]+).(it|com|net|org)"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="password">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="4"/>
									<xs:maxLength value="8"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="nome" type="xs:string" />
						<xs:element name="cognome" type="xs:string" minOccurs="0" />
						<xs:element name="indirizzo" type="ind" />
						<xs:element name="fatturazione" type="xs:string" minOccurs="0" />
						<xs:element name="tipo_fatt" type="xs:string" minOccurs="0" />
						<xs:element name="admin">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="si|no" />
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
				<xs:complexType name="ind">
					<xs:sequence>
						<xs:element name="via" type="xs:string" />
						<xs:element name="numero">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="([0-9])+[a|b|c|d|e|f|g|h|i|l|m]*" />
									<xs:maxLength value="4" />
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="paese" type="xs:string" />
						<xs:element name="provincia" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:schema>

=== giovanni-venturelli/arsr/daUppare/data/login.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xmlns = "http://www.ASRS.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="login.xsd"?>
<login>
	<utente>
		<username>frossi</username>
		<email>frossi@gmail.com</email>
		<password>fabiorossi</password>
		<nome>Fabio</nome>
		<cognome>Rossi</cognome>
		<indirizzo>
			<via>via uruguay</via>
			<numero>10</numero>
			<paese>Italia</paese>
			<provincia>Vicenza</provincia>
		</indirizzo>
		<fatturazione>GMTLKS45862DF89S</fatturazione>
        <tipo_fatt>p.iva</tipo_fatt>
        <admin>no</admin>
	</utente>		
	<utente>
		<username>francesco10</username>
		<email>francesco.p@gmail.com</email>
		<password>francesco18</password>
		<nome>Prancesco</nome>
		<cognome>Palermo</cognome>
		<indirizzo>
			<via>Via Marin</via>
			<numero>57</numero>
			<paese>Italia</paese>
			<provincia>Padova</provincia>
		</indirizzo>
		<fatturazione>GNTMTT91M705S</fatturazione>
		<tipo_fatt>cod.fiscale</tipo_fatt>
		<admin>no</admin>
	</utente>
	<utente>
		<username>admin1</username>
		<email>amministrazione@arsr.com</email>
		<password>amministratore1</password>
		<nome>Francesco</nome>
		<cognome>Agostini</cognome>
		<indirizzo>
			<via>via Roma</via>
			<numero>75</numero>
			<paese>Italia</paese>
			<provincia>Padova</provincia>
		</indirizzo>
		<admin>si</admin>
	</utente>
		
	<utente>
		<username>alessiaT</username>
		<email>alessia_tomba@hotmail.com</email>
		<password>alessia92</password>
		<nome>Alessia</nome>
		<cognome>Tomba</cognome>
		<indirizzo>
			<via>via XX settembre</via>
			<numero>1</numero>
			<paese>Italia</paese>
			<provincia>Verona</provincia>
		</indirizzo>
		<admin>no</admin>
	</utente>	
</login>
